version: 2
jobs:
  analyze:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run:
          name: Analyze files
          command: flutter analyze

  test:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run:
          name: Test code
          command: flutter test

workflows:
  version: 2
  lint_and_test:
    jobs:
      - analyze
      - test

